This is an supervised learning technique to obtain a word embeddings (Vector). 

In [2]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten , Embedding
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences

We obtain a word vector by performing some any dummy operation on text corpus.

The below text data which is used to obtain a word embedding, <mark  style = "background-color:khaki;">  but vectors are viable & reliable when they trained on large corpus. </mark>

In [3]:
reviews = [ 'nice food',
            'amazing restaurant ',
            'too good' ,
            'just loved it' ,
            'will go again',
            'horrible food' ,
            'never go there' ,
            'poor service' ,
            'poor quality ' ,
            'needs improvement' ] 

sentiment = [1, 1, 1, 1, 1, 0, 0, 0, 0, 0]

Data preprocessing | Feature Engineering

In [4]:
i = 0  
print(reviews[i], one_hot(reviews[i],10), sep=' - > ')

nice food - > [2, 5]


In [33]:
vocab_size = 40
ohe_reviews = [ one_hot(d, vocab_size) for d in reviews ]

ohe_reviews

[[38, 14],
 [39, 27],
 [20, 4],
 [39, 9, 33],
 [3, 3, 3],
 [32, 14],
 [16, 3, 6],
 [31, 25],
 [31, 12],
 [10, 29]]

In [34]:
# Function to get optimal input_len

def get_len(ohe_data ,by = 0):
    return max( [ len(i) for i in ohe_data ] ) + by
    
input_len = get_len(ohe_reviews)
x = pad_sequences(ohe_reviews, maxlen=input_len, padding='post')
x

array([[38, 14,  0],
       [39, 27,  0],
       [20,  4,  0],
       [39,  9, 33],
       [ 3,  3,  3],
       [32, 14,  0],
       [16,  3,  6],
       [31, 25,  0],
       [31, 12,  0],
       [10, 29,  0]])

- Model building

In [35]:
import numpy as np

X=x
Y = np.array(sentiment)
Y.reshape(-1,1)

array([[1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0]])

In [36]:
output_dim = 4

model = Sequential()
model.add(Embedding( vocab_size, output_dim, input_length = input_len, name = 'embedding'  ))
model.add(Flatten())
model.add(Dense(1, activation = 'sigmoid'))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 3, 4)              160       
                                                                 
 flatten_1 (Flatten)         (None, 12)                0         
                                                                 
 dense_1 (Dense)             (None, 1)                 13        
                                                                 
Total params: 173
Trainable params: 173
Non-trainable params: 0
_________________________________________________________________


In [37]:
model.compile(
    
    optimizer = 'adam',
    
    loss = 'binary_crossentropy',
    
    metrics = ['accuracy']
)

In [41]:
model.fit(X, Y, epochs=50,verbose= 0)

In [42]:
vectors = model.get_layer("embedding").get_weights()[0]
len(vectors)

40

In [43]:
j = 0
for i in reviews:
    print(i,' - >  ',x[j])
    j -=- 1

nice food  - >   [38 14  0]
amazing restaurant   - >   [39 27  0]
too good  - >   [20  4  0]
just loved it  - >   [39  9 33]
will go again  - >   [3 3 3]
horrible food  - >   [32 14  0]
never go there  - >   [16  3  6]
poor service  - >   [31 25  0]
poor quality   - >   [31 12  0]
needs improvement  - >   [10 29  0]


<mark style = "background-color: darkcyan;"> Select the vectors on basis of words index which are illustrated above. </mark>

In [46]:
vectors[38] # For word ' nice '

array([0.10989111, 0.14360538, 0.1652687 , 0.17399621], dtype=float32)

In [47]:
vectors[39] # For word ' Amazing ' 

array([0.1857583 , 0.15475813, 0.16207132, 0.16707481], dtype=float32)

1. This is the similarity score between the word <mark> amazing </mark> and <mark> nice. </mark>

In [70]:
from sklearn.metrics.pairwise import *

score = cosine_similarity( vectors[38].reshape(1,-1),vectors[39].reshape(1,-1) )
print('Similarity score - ' + str(score[0][0]))

Similarity score - 0.9766783


1. This is the similarity score between the word <mark> horrible  </mark> and <mark> poor. </mark>

In [73]:
score = cosine_similarity( vectors[32].reshape(1,-1),vectors[31].reshape(1,-1) )
print('Similarity score - ' + str(score[0][0]))

Similarity score - 0.9777903



<h2 style = "color:darkgray;">' CONCLUSIVELY WE OBTAINED THE RESULTS '</h2>
